spring:
  application:
    name: ${API_GATEWAY_HOST}
  cloud:
    gateway:
      routes:
        - id: ${AUTHENTICATION_SERVICE_HOST}
          uri: lb://${AUTHENTICATION_SERVICE_HOST}
          predicates:
            - Path=/api/v1/auth/**
        - id: ${AUTHENTICATION_SERVICE_HOST}
          uri: lb://${AUTHENTICATION_SERVICE_HOST}
          predicates:
            - Path=/api/v1/test/**
        - id: ${PRODUCT_MANAGER_SERVICE_HOST}
          uri: lb://${PRODUCT_MANAGER_SERVICE_HOST}
          predicates:
            - Path=/api/v1/product/**

eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST}:${SERVICE_DISCOVERY_PORT_INNER}/eureka
    register-with-eureka: true
    fetch-registry: true

jwt:
  starter:
    secret: ${JWT_SECRET}
    lifetime: ${JWT_LIFETIME}

server:
  port: ${API_GATEWAY_PORT_INNER}
